<a href="https://colab.research.google.com/github/ayush1011-gsv/PCA-lab/blob/main/AILM(oop)_assig_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PCA (principal component analysis)

In [ ]:
import numpy as np
import pandas as pd
data={'x':[7,4,6,8,8,7,5,9,7,8],
      'y':[4,1,3,6,5,2,3,5,4,2]}
data=pd.DataFrame(data)
x_mean=data["x"].mean()
y_mean=data["y"].mean()

data["x-mean(x)"]=data['x']-x_mean
data["y-mean(y)"]=data['y']-y_mean

data["(x-mean(x))^2"]=(data["x"]-x_mean)**2
data["(y-mean(y))^2"]=(data['y']-y_mean)**2
data["(x-mean(x))(y-mean(y))"]=data["x-mean(x)"]*data['y-mean(y)']

variance_x=data["(x-mean(x))^2"].sum() / (data["(x-mean(x))^2"].count()-1)
variance_y=data["(y-mean(y))^2"].sum() / (data["(y-mean(y))^2"].count()-1)

covariance=data["(x-mean(x))(y-mean(y))"].sum() / (data["(x-mean(x))(y-mean(y))"].count() -1)
display(data)

print("\nvarince of x: ",variance_x,"\nvarince of y: ",variance_y)
print("\ncovarince: ",covariance)

covariance_matrix=np.array([[variance_x,covariance],[covariance,variance_y]])
print("\ncovarince matrix: \n",covariance_matrix)

eigenvalue,noraml_eigenvector=np.linalg.eig(covariance_matrix)
print("\neigenvalue: ")
print(eigenvalue)
print("\nnormal eigenvector")
print(noraml_eigenvector)

sorted_indices=np.argsort(eigenvalue)[::-1]
sorted_eigenvalue = eigenvalue[sorted_indices]
sorted_eigenvector=noraml_eigenvector[:,sorted_indices]# larger vecoter at 1st col
pc1_vector=-1*sorted_eigenvector[:,0]

print("\n 1st principle component vectoer :",pc1_vector)
centered_data=data[['x-mean(x)','y-mean(y)']].values
data["pc1"]=np.dot(centered_data,pc1_vector)
display(data[['x','y','pc1']])

,x,y,x-mean(x),y-mean(y),(x-mean(x))^2,(y-mean(y))^2,(x-mean(x))(y-mean(y))
0,7,4,0.1,0.5,0.01,0.25,0.05
1,4,1,-2.9,-2.5,8.41,6.25,7.25
2,6,3,-0.9,-0.5,0.81,0.25,0.45
3,8,6,1.1,2.5,1.21,6.25,2.75
4,8,5,1.1,1.5,1.21,2.25,1.65
5,7,2,0.1,-1.5,0.01,2.25,-0.15
6,5,3,-1.9,-0.5,3.61,0.25,0.95
7,9,5,2.1,1.5,4.41,2.25,3.15
8,7,4,0.1,0.5,0.01,0.25,0.05
9,8,2,1.1,-1.5,1.21,2.25,-1.65

varince of x:  2.3222222222222224
varince of y:  2.5

covarince:  1.6111111111111116

covarince matrix:
 [[2.32222222 1.61111111]
 [1.61111111 2.5       ]]

eigenvalue:
[0.79754976 4.02467247]

normal eigenvector
[[-0.72632246 -0.68735412]
 [ 0.68735412 -0.72632246]]

 1st principle component vectoer : [0.68735412 0.72632246]

   x  y       pc1
0  7  4  0.431897
1  4  1 -3.809133
2  6  3 -0.981780
3  8  6  2.571896
4  8  5  1.845573
5  7  2 -1.020748
6  5  3 -1.669134
7  9  5  2.532927
8  7  4  0.431897
9  8  2 -0.333394